### ISSUE TITLE
Stage 3 readiness review

### ISSUE THREAD

**Issue by FrankYFTang** [FrankYFTang/proposal-intl-extend-timezonename#5]
Please raise issue of the current spec text if you see anything missing for Stage 3.

 @ptomato @rickbutton

**Comment by ptomato** [comment]
Thanks! I took a look at it and opened one discussion. (Note this isn't a full review — I'd like to do that closer to the time that you plan to request Stage 3.) Do you have an expectation of what might change between now and Stage 3?

**Comment by FrankYFTang** [comment]
> Do you have an expectation of what might change between now and Stage 3?

Currently, there are nothing I plan to change. If there are suggestion to improve the spec text and agree upon ECMA402 TC-TG2 then I will change based on the request.

**Comment by FrankYFTang** [comment]
@rickbutton @ptomato I would like to talk about this proposal in TG2 (ECMA402) tomorrow for getting support for Stage 3 in TC39 May 21 meeting. Any issues beside https://github.com/tc39/proposal-intl-extend-timezonename/issues/7 ?
@anba @zbraniecki  - Also would appreciate if you have concern voice that earlier.

**Comment by anba** [comment]
> @anba @zbraniecki - Also would appreciate if you have concern voice that earlier.

ECMA-402 doesn't properly handle time zones in [FormatDateTimePattern](https://tc39.es/ecma402/#sec-formatdatetimepattern), because `FormatDateTimePattern` has the same issue as tc39/ecma402#515, i.e. it tries to read [[TimeZoneName]] from the record returned from [ToLocalTime](https://tc39.es/ecma402/#sec-tolocaltime), but `ToLocalTime` doesn't actually return a [[TimeZoneName]] field.

That issue makes it somewhat annoying to review this proposal, because we add more undefined behaviour on top of already undefined behaviour. :smile: 

---

Apart from that:

In the modified [FormatDateTimePattern](https://tc39.es/proposal-intl-extend-timezonename/#sec-formatdatetimepattern) algorithm, steps 15.e.xi-xii:
- No comma before the "or" in:
  > Else if f is "shortGeneric", or "longGeneric", then
- Use "or" instead of a comma in:
  > Else if f is "shortOffset", "longOffset" then
- I can't tell if [[InDST]] needs to be handled for "shortOffset" and "longOffset", because [[TimeZoneName]] isn't defined (see above).

In the modified [BasicFormatMatcher](https://tc39.es/proposal-intl-extend-timezonename/#sec-basicformatmatcher) algorithm:
- The penalty computation doesn't seem correct.

Using the data from <https://unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns>, we get this table:
Name | Example | Pattern | Fallback | Note
-----|---------|---------|----------|-----
short        | PDT                   | z    | O |
long         | Pacific Daylight Time | zzzz | OOOO |
shortOffset  | GMT-7                 | O    | - |
longOffset   | GMT-07:00             | OOOO | - |
shortGeneric | PT                    | v    | VVVV, O | VVVV fallback changed to O
longGeneric  | Pacific Time          | vvvv | VVVV |
|-            | Los Angeles Time      | VVVV | OOOO |

That means for example when "short" (z) is requested, but not available, and "long" (zzzz) and "shortOffset" (O) are both available, the current penalty computation will prefer "long" (zzzz), but per UTS 35 "shortOffset" (O) should be preferred. 

I can't answer offhand what should be the correct order of the property values in `BasicFormatMatcher` or even if the current approach does actually work at all for the new time zone options. You'd need to list all possible options and compare them to each other (= Cartesian product) to find how to order them. And if that doesn't work, `BasicFormatMatcher` may need to be changed to handle time zones names separately.

**Comment by FrankYFTang** [comment]
@anba - I fixed the "or" and "," issue. For FormatDateTimePattern  
Please see 
https://github.com/tc39/proposal-intl-extend-timezonename/pull/9/files
and also https://github.com/tc39/ecma402/pull/573

I will dig into " BasicFormatMatcher algorithm" more later next week.

**Comment by ptomato** [comment]
@FrankYFTang Are you planning to request Stage 3 in the upcoming May TC39 meeting? If so, would you mind pinging me again on this thread when you have finished digging into the BasicFormatMatcher algorithm so I can do a final review?

**Comment by FrankYFTang** [comment]
> @FrankYFTang Are you planning to request Stage 3 in the upcoming May TC39 meeting? If so, would you mind pinging me again on this thread when you have finished digging into the BasicFormatMatcher algorithm so I can do a final review?

YES I am. YES I will.

**Comment by FrankYFTang** [comment]
So from what I read on https://unicode.org/reports/tr35/tr35-dates.html#Time_Zone_Goals

short fallback to shortOffset
shortGeneric fallback to shortOffset
long fallback to longOffset
longGeneric fallback to longOffset

**Comment by FrankYFTang** [comment]
@ptomato  @rickbutton
Any concerns of comments?

**Comment by rickbutton** [comment]
No comments, it doesn't look like anything is missing for Stage 3.

🎉

**Comment by codehag** [comment]
Prototype from mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1710429

**Comment by ptomato** [comment]
For the record, I gave my reviewer signoff live in the plenary.

**Comment by FrankYFTang** [comment]
since we now moved to Stage 3. Close this issue.
